# Copyright (c) 2009-2010 Satoshi Nakamoto
# Copyright (c) 2014-2026 The InfiniteRicks developers
# Distributed under the MIT/X11 software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# 64-bit Windows is required (__int128 is not available on i686-w64-mingw32).
TARGET_PLATFORM?=x86_64
#TARGET_PLATFORM:=i686

DEPSDIR?=$(HOME)/.infinite-ricks/mingw-deps

CC?=$(TARGET_PLATFORM)-w64-mingw32-gcc
CXX?=$(TARGET_PLATFORM)-w64-mingw32-g++
RANLIB?=$(TARGET_PLATFORM)-w64-mingw32-ranlib
STRIP?=$(TARGET_PLATFORM)-w64-mingw32-strip

USE_UPNP:=0
BOOST_LIB_SUFFIX?=

INCLUDEPATHS= \
 -I"$(CURDIR)" \
 -I"$(CURDIR)"/obj \
 -I"$(DEPSDIR)/include" \
 -I"$(DEPSDIR)/include/miniupnpc"

LIBPATHS= \
 -L"$(DEPSDIR)/lib"

LIBS= \
 -lboost_system$(BOOST_LIB_SUFFIX) \
 -lboost_filesystem$(BOOST_LIB_SUFFIX) \
 -lboost_program_options$(BOOST_LIB_SUFFIX) \
 -lboost_thread$(BOOST_LIB_SUFFIX) \
 -lboost_chrono$(BOOST_LIB_SUFFIX) \
 -ldb_cxx \
 -lssl \
 -lcrypto \
 -lcrypt32 \
 -lz

DEFS=-D_MT -DWIN32 -D_WINDOWS -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -Wno-deprecated-declarations
DEBUGFLAGS=-g
CFLAGS=-O2 -msse2 -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter $(DEBUGFLAGS) $(DEFS) $(INCLUDEPATHS)
LDFLAGS=-Wl,--dynamicbase -Wl,--nxcompat -static-libgcc -static-libstdc++

ifndef USE_UPNP
	override USE_UPNP = -
endif
ifneq (${USE_UPNP}, -)
	LIBS += -lminiupnpc -liphlpapi
	DEFS += -DSTATICLIB -DMINIUPNP_STATICLIB -DUSE_UPNP=$(USE_UPNP)
endif

LIBS += -lmingwthrd -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lws2_32 -lmswsock -lshlwapi

HEADERS = $(wildcard *.h)

OBJS= \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/key.o \
    obj/db.o \
    obj/init.o \
    obj/irc.o \
    obj/keystore.o \
    obj/main.o \
    obj/miner.o \
    obj/net.o \
    obj/protocol.o \
    obj/bitcoinrpc.o \
    obj/rpcclient.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/rpcrawtransaction.o \
    obj/script.o \
    obj/sync.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/noui.o \
    obj/kernel.o \
    obj/pbkdf2.o \
    obj/scrypt.o \
    obj/scrypt-x86.o \
    obj/scrypt-x86_64.o \
    obj/zerocoin/Accumulator.o \
    obj/zerocoin/AccumulatorProofOfKnowledge.o \
    obj/zerocoin/Coin.o \
    obj/zerocoin/CoinSpend.o \
    obj/zerocoin/Commitment.o \
    obj/zerocoin/ParamGeneration.o \
    obj/zerocoin/Params.o \
    obj/zerocoin/SerialNumberSignatureOfKnowledge.o \
    obj/zerocoin/SpendMetaData.o \
    obj/zerocoin/ZeroTest.o

all: InfiniteRicksd.exe InfiniteRicks-cli.exe InfiniteRicks-tx.exe

TOOL_LIBS= \
 -l boost_system-mgw44-mt-1_53 \
 -l boost_filesystem-mgw44-mt-1_53 \
 -l boost_program_options-mgw44-mt-1_53 \
 -l boost_thread-mgw44-mt-1_53 \
 -l boost_chrono-mgw44-mt-1_53 \
 -l ssl \
 -l crypto \
 -l kernel32 -l user32 -l gdi32 -l winspool -l shell32 -l ole32 -l oleaut32 -l uuid -l rpcrt4 -l advapi32 -l ws2_32 -l mswsock -l shlwapi

CLI_OBJS= \
    obj/infinitericks-cli.o \
    obj/rpcclient.o \
    obj/util.o \
    obj/netbase.o \
    obj/version.o \
    obj/sync.o \
    obj/noui.o

TX_OBJS= \
    obj/infinitericks-tx.o \
    obj/txtools.o \
    obj/script.o \
    obj/util.o \
    obj/netbase.o \
    obj/version.o \
    obj/sync.o \
    obj/noui.o \
    obj/key.o \
    obj/keystore.o \
    obj/crypter.o \
    obj/pbkdf2.o \
    obj/scrypt.o \
    obj/scrypt-x86_64.o

LIBS += $(CURDIR)/leveldb/libleveldb.a $(CURDIR)/leveldb/libmemenv.a
DEFS += -I"$(CURDIR)/leveldb/include"
DEFS += -I"$(CURDIR)/leveldb/helpers"
OBJS += obj/txdb-leveldb.o
leveldb/libleveldb.a:
	@echo "Building LevelDB ..." && cd leveldb && CC=$(CC) CXX=$(CXX) TARGET_OS=OS_WINDOWS_CROSSCOMPILE $(MAKE) libleveldb.a libmemenv.a && $(RANLIB) libleveldb.a && $(RANLIB) libmemenv.a && cd ..
obj/txdb-leveldb.o: leveldb/libleveldb.a

obj/build.h: FORCE
	@mkdir -p obj obj/zerocoin
	/bin/sh ../share/genbuild.sh obj/build.h
version.cpp: obj/build.h
DEFS += -DHAVE_BUILD_INFO

obj/%.o: %.cpp $(HEADERS)
	$(CXX) -c $(CFLAGS) -o $@ $<

obj/zerocoin/%.o: zerocoin/%.cpp $(HEADERS)
	$(CXX) -c $(CFLAGS) -o $@ $<

InfiniteRicksd.exe: $(OBJS:obj/%=obj/%)
	$(CXX) $(CFLAGS) $(LDFLAGS) -o $@ $(LIBPATHS) $^ $(LIBS) -lshlwapi -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic
	$(STRIP) InfiniteRicksd.exe

InfiniteRicks-cli.exe: $(CLI_OBJS)
	$(CXX) $(CFLAGS) $(LDFLAGS) -o $@ $(LIBPATHS) $^ $(TOOL_LIBS)
	$(STRIP) InfiniteRicks-cli.exe

InfiniteRicks-tx.exe: $(TX_OBJS)
	$(CXX) $(CFLAGS) $(LDFLAGS) -o $@ $(LIBPATHS) $^ $(TOOL_LIBS)
	$(STRIP) InfiniteRicks-tx.exe

obj/scrypt-x86.o: scrypt-x86.S
	$(CXX) -c $(CFLAGS) -MMD -o $@ $<

obj/scrypt-x86_64.o: scrypt-x86_64.S
	$(CXX) -c $(CFLAGS) -MMD -o $@ $<

clean:
	-rm -f obj/*.o
	-rm -f obj/zerocoin/*.o
	-rm -f InfiniteRicksd.exe InfiniteRicks-cli.exe InfiniteRicks-tx.exe
	-rm -f obj/build.h
	cd leveldb && TARGET_OS=OS_WINDOWS_CROSSCOMPILE $(MAKE) clean && cd ..

FORCE:
